### ISSUE TITLE
CEO crash related to CEO golf attack

### ISSUE THREAD

**Issue by DankMickey** [Toontown-Rewritten-Private/TTR-Private#15]
Traceback (most recent call last):
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\otp\distributed\OTPClientRepository.py", line 1559, in handlePlayGame
    self.handleUpdateField(di)
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\distributed\ClientRepositoryBase.py", line 437, in handleUpdateField
    self.__doUpdate(doId, di, ovUpdated)
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\distributed\ClientRepositoryBase.py", line 445, in __doUpdate
    do.dclass.receiveUpdate(do, di)
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\toontown\suit\DistributedBossbotBoss.py", line 977, in setAttackCode
    self.doGolfAttack(avId, attackCode)
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\toontown\suit\DistributedBossbotBoss.py", line 1347, in doGolfAttack
    seq = Sequence(ParallelEndTogether(self.pelvis.hprInterval(1, VBase3(toToonH, 0, 0)), neutral1Anim), extraAnim, Parallel(Sequence(Wait(0.19), gearTrack, Func(detachGearRootLater), self.pelvis.hprInterval(0.2, VBase3(0, 0, 0))), Sequence(throwAnim, neutral2Anim), Sequence(Wait(0.85), SoundInterval(self.swingClubSfx, node=self, duration=0.45, cutOff=300, listenerNode=base.localAvatar))))
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\interval\MetaInterval.py", line 117, in __init__
    assert self.validateComponents(self.ivals)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\otp\otpbase\OTPBase.py", line 238, in run
    taskMgr.run()
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\task\Task.py", line 553, in run
    self.step()
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\task\Task.py", line 504, in step
    self.mgr.poll()
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\distributed\ConnectionRepository.py", line 610, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\distributed\ConnectionRepository.py", line 617, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\otp\distributed\OTPClientRepository.py", line 1959, in handleDatagram
    self.handler(msgType, di)
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\otp\distributed\OTPClientRepository.py", line 1561, in handlePlayGame
    self.notify.warning('AssertionError: %s' % e.message)
AttributeError: 'AssertionError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\toontown\toonbase\ToontownStart.py", line 256, in <module>
    base.run()
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\otp\otpbase\OTPBase.py", line 249, in run
    self.cr.timeManager.setExceptionInfo()
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\otp\ai\TimeManager.py", line 160, in setExceptionInfo
    self.sendUpdate('setExceptionInfo', [info])
  File "C:\Users\USER\Documents\GitHub\TTR-Offline\Panda3D-1.10.11\direct\distributed\DistributedObject.py", line 364, in sendUpdate
    dg = self.dclass.clientFormatUpdate(
ValueError: Value out of range on field: setExceptionInfo['Traceback (most recent call last):\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\otp\\distributed\\OTPClientRepository.py", line 1559, in handlePlayGame\n    self.handleUpdateField(di)\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\distributed\\ClientRepositoryBase.py", line 437, in handleUpdateField\n    self.__doUpdate(doId, di, ovUpdated)\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\distributed\\ClientRepositoryBase.py", line 445, in __doUpdate\n    do.dclass.receiveUpdate(do, di)\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\toontown\\suit\\DistributedBossbotBoss.py", line 977, in setAttackCode\n    self.doGolfAttack(avId, attackCode)\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\toontown\\suit\\DistributedBossbotBoss.py", line 1347, in doGolfAttack\n    seq = Sequence(ParallelEndTogether(self.pelvis.hprInterval(1, VBase3(toToonH, 0, 0)), neutral1Anim), extraAnim, Parallel(Sequence(Wait(0.19), gearTrack, Func(detachGearRootLater), self.pelvis.hprInterval(0.2, VBase3(0, 0, 0))), Sequence(throwAnim, neutral2Anim), Sequence(Wait(0.85), SoundInterval(self.swingClubSfx, node=self, duration=0.45, cutOff=300, listenerNode=base.localAvatar))))\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\interval\\MetaInterval.py", line 117, in __init__\n    assert self.validateComponents(self.ivals)\nAssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\otp\\otpbase\\OTPBase.py", line 238, in run\n    taskMgr.run()\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\task\\Task.py", line 553, in run\n    self.step()\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\task\\Task.py", line 504, in step\n    self.mgr.poll()\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\distributed\\ConnectionRepository.py", line 610, in readerPollUntilEmpty\n    while self.readerPollOnce():\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\Panda3D-1.10.11\\direct\\distributed\\ConnectionRepository.py", line 617, in readerPollOnce\n    self.handleDatagram(self.private__di)\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\otp\\distributed\\OTPClientRepository.py", line 1959, in handleDatagram\n    self.handler(msgType, di)\n  File "C:\\Users\\USER\\Documents\\GitHub\\TTR-Offline\\otp\\distributed\\OTPClientRepository.py", line 1561, in handlePlayGame\n    self.notify.warning(\'AssertionError: %s\' % e.message)\nAttributeError: \'AssertionError\' object has no attribute \'message\'\n']
Press any key to continue . . .

**Comment by RegDogg** [comment]
Fixed in https://github.com/Toontown-Rewritten-Offline/TTR-Offline/commit/e5b85f4f48b6f2f0f143c756c134b387d4b19f2e
