### ISSUE TITLE
Game crashes when moving zones

### ISSUE THREAD

**Issue by DarthMDev** [Toontown-Rewritten-Private/TTR-Private#4]
```
Traceback (most recent call last):
  File "/Users/michael/github/TTR-Private/src/otp/otpbase/OTPBase.py", line 238, in run
    taskMgr.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/task/Task.py", line 546, in run
    self.step()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/task/Task.py", line 497, in step
    self.mgr.poll()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/distributed/ConnectionRepository.py", line 613, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/distributed/ConnectionRepository.py", line 620, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "/Users/michael/github/TTR-Private/src/otp/distributed/OTPClientRepository.py", line 1959, in handleDatagram
    self.handler(msgType, di)
  File "/Users/michael/github/TTR-Private/src/toontown/hood/QuietZoneState.py", line 156, in handleWaitForQuietZoneResponse
    base.cr.handlePlayGame(msgType, di)
  File "/Users/michael/github/TTR-Private/src/otp/distributed/OTPClientRepository.py", line 1565, in handlePlayGame
    self.handleMessageType(msgType, di)
  File "/Users/michael/github/TTR-Private/src/otp/distributed/OTPClientRepository.py", line 1853, in handleMessageType
    self.gotInterestDoneMessage(di)
  File "/Users/michael/github/TTR-Private/src/otp/distributed/OTPClientRepository.py", line 1881, in gotInterestDoneMessage
    self.handleInterestDoneMessage(di)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/distributed/DoInterestManager.py", line 641, in handleInterestDoneMessage
    messenger.send(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/showbase/Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/showbase/Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/Users/michael/github/TTR-Private/src/toontown/distributed/ToontownClientRepository.py", line 1027, in _handleEmuSetZoneDone
    messenger.send(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/showbase/Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/showbase/Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/Users/michael/github/TTR-Private/src/toontown/hood/QuietZoneState.py", line 199, in _handleQuietZoneComplete
    self.fsm.request('waitForZoneRedirect')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "/Users/michael/github/TTR-Private/src/toontown/hood/QuietZoneState.py", line 240, in enterWaitForZoneRedirect
    self.fsm.request('waitForSetZoneResponse')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/fsm/State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "/Users/michael/github/TTR-Private/src/toontown/hood/QuietZoneState.py", line 264, in enterWaitForSetZoneResponse
    base.cr.sendSetZoneMsg(zoneId)
  File "/Users/michael/github/TTR-Private/src/toontown/distributed/ToontownClientRepository.py", line 985, in sendSetZoneMsg
    localAvatar.setLocation(parentId, zoneId)
  File "/Users/michael/github/TTR-Private/src/otp/avatar/DistributedPlayer.py", line 91, in setLocation
    DistributedAvatar.DistributedAvatar.setLocation(self, parentId, zoneId)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/distributed/DistributedNode.py", line 45, in setLocation
    DistributedObject.DistributedObject.setLocation(self, parentId, zoneId)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/direct/distributed/DistributedObject.py", line 498, in setLocation
    self.cr.storeObjectLocation(self, parentId, zoneId)
AttributeError: 'NoneType' object has no attribute 'storeObjectLocation'
```

**Comment by RegDogg** [comment]
Yep, thanks for pointing this issue out again, especially on GitHub, this is due to the version of Astron being used, now that it is here, we can work through it, I will look into TTR Private with a newer version of Astron tomorrow!

**Comment by DarthMDev** [comment]
Let me know when you get to it i can help you compile a universal2 build with intel and m1 support i already have the universal2 builds compiled for the dependencies

**Comment by RegDogg** [comment]
Issue fixed on commit 
06814d6f0580e2159d386e0c276e0ef45a5afa0a
